filename: teste.csv

device: cuda

runs: 1

models: 
  - c22
  # - tsfresh
  # - multirocket_fm
  # - DrCIF
  # - MiniRocket

task: tsc

data_path: data

seed: 0

datasets:

  # - Covid3Month
  # - FloodModeling1
  # - FloodModeling2
  # - FloodModeling3
  # - IEEEPPG
  # - HouseholdPowerConsumption2_nmv
  # - HouseholdPowerConsumption1_nmv
  # - AppliancesEnergy
  # - BenzeneConcentration_nmv
  # - LiveFuelMoistureContent
  # - BIDMC32RR
  # - BIDMC32SpO2
  # - BIDMC32HR

  # - AcousticContaminationMadrid_nmv
  # - AluminiumConcentration
  # - BarCrawl6min
  # - BeijingIntAirportPM25Quality
  # - BinanceCoinSentiment
  # - BitcoinSentiment
  # - BoronConcentration
  # - CalciumConcentration
  # - CardanoSentiment
  # - ChilledWaterPredictor
  # - CopperConcentration
  # - Covid19Andalusia
  # - DailyOilGasPrices
  # - DhakaHourlyAirQuality
  # - ElectricityPredictor
  # - EthereumSentiment
  # - GasSensorArrayAcetone
  # - GasSensorArrayEthanol
  # - HotwaterPredictor
  # - IronConcentration
  # - LPGasMonitoringHomeActivity
  # - MadridPM10Quality_nmv

  # - MagnesiumConcentration
  # - ManganeseConcentration
  # - MethaneMonitoringHomeActivity
  # - MetroInterstateTrafficVolume
  # - NaturalGasPricesSentiment
  # - OccupancyDetectionLight
  # - ParkingBirmingham_eq
  # - PhosphorusConcentration
  # - PotassiumConcentration
  # - PrecipitationAndalusia_nmv
  # - SierraNevadaMountainsSnow
  # - SodiumConcentration
  # - SolarRadiationAndalusia_nmv
  # - SteamPredictor
  # - SulphurConcentration
  # - WaveDataTension
  # - WindTurbinePower
  # - ZincConcentration
  # - BeijingPM10Quality_nmv
  # - BeijingPM25Quality_nmv
  
  # Big
  # - ElectricMotorTemperature
  # - DailyTemperatureLatitude
  # - TetuanEnergyConsumption
  # - PPGDalia_eq
  # - NewsHeadlineSentiment
  # - NewsTitleSentiment
  # - VentilatorPressure
  # - AustraliaRainfall

  # ----------------------------------------------------------------------------

  # Class
  # - Adiac
  # - ArticularyWordRecognition
  # - Cricket
  # - CricketX
  # - CricketY
  # - CricketZ
  # - EOGHorizontalSignal
  # - EOGVerticalSignal
  # - FacesUCR
  # - FiftyWords
  # - Fungi
  # - GestureMidAirD1
  # - GestureMidAirD2
  # - GestureMidAirD3
  # - Handwriting
  # - FaceAll
  # - InsectWingbeatSound
  # - Libras
  # - LSST
  # - MiddlePhalanxTW
  # - NonInvasiveFetalECGThorax1
  # - NonInvasiveFetalECGThorax2
  # - Phoneme
  # - PhonemeSpectra
  # - PigAirwayPressure
  # - PigArtPressure
  # - PigCVP
  # - PLAID
  # - ShapesAll
  # - SwedishLeaf
  # - WordSynonyms
  # - Crop

  # ShapeDiff
  # - AllGestureWiimoteX
  # - AllGestureWiimoteY
  # - AllGestureWiimoteZ

  # Missing
  # - DodgerLoopDay
  # - DodgerLoopGame
  # - DodgerLoopWeekend
  # - MelbournePedestrian
  # - CharacterTrajectories

  # Zero division
  # - Earthquakes
  # - InsectWingbeat
  # - MotorImagery
  # - DistalPhalanxTW

  - ArrowHead
  # - AtrialFibrillation
  # - ACSF1
  # - BasicMotions
  # - Beef
  # - BeetleFly
  # - BirdChicken
  # - BME
  # - Car
  # - CBF
  # - Chinatown
  # - ChlorineConcentration
  # - CinCECGTorso
  # - Coffee
  # - Computers
  # - DiatomSizeReduction
  # - DistalPhalanxOutlineAgeGroup
  # - DistalPhalanxOutlineCorrect
  # - DuckDuckGeese
  # - ECG200
  # - ECG5000
  # - ECGFiveDays
  # - EigenWorms
  # - ElectricDevices
  # - Epilepsy
  # - ERing
  # - EthanolConcentration
  # - EthanolLevel  
  # - FaceDetection
  # - FaceFour
  # - FingerMovements
  # - Fish
  # - FordA
  # - FordB
  # - FreezerRegularTrain
  # - FreezerSmallTrain
  # - GesturePebbleZ1
  # - GesturePebbleZ2
  # - GunPoint
  # - GunPointAgeSpan
  # - GunPointMaleVersusFemale
  # - GunPointOldVersusYoung
  # - Ham
  # - HandMovementDirection
  # - HandOutlines
  # - Haptics
  # - Heartbeat
  # - Herring
  # - HouseTwenty
  # - InlineSkate
  # - InsectEPGRegularTrain
  # - InsectEPGSmallTrain
  # - ItalyPowerDemand
  # - JapaneseVowels
  # - LargeKitchenAppliances
  # - Lightning2
  # - Lightning7
  # - Mallat
  # - Meat
  # - MedicalImages
  # - MiddlePhalanxOutlineAgeGroup
  # - MiddlePhalanxOutlineCorrect
  # - MixedShapesRegularTrain
  # - MixedShapesSmallTrain
  # - MoteStrain
  # - NATOPS
  # - OliveOil
  # - OSULeaf
  # - PEMS-SF
  # - PenDigits
  # - PhalangesOutlinesCorrect
  # - PickupGestureWiimoteZ
  # - Plane
  # - PowerCons
  # - ProximalPhalanxOutlineAgeGroup
  # - ProximalPhalanxOutlineCorrect
  # - ProximalPhalanxTW
  # - RacketSports
  # - RefrigerationDevices
  # - Rock
  # - ScreenType
  # - SelfRegulationSCP1
  # - SelfRegulationSCP2
  # - SemgHandGenderCh2
  # - SemgHandMovementCh2
  # - SemgHandSubjectCh2
  # - ShakeGestureWiimoteZ
  # - ShapeletSim
  # - SmallKitchenAppliances
  # - SmoothSubspace
  # - SonyAIBORobotSurface1
  # - SonyAIBORobotSurface2
  # - SpokenArabicDigits
  # - StandWalkJump
  # - StarLightCurves
  # - Strawberry
  # - Symbols
  # - SyntheticControl
  # - ToeSegmentation1
  # - ToeSegmentation2
  # - Trace
  # - TwoLeadECG
  # - TwoPatterns
  # - UMD
  # - UWaveGestureLibrary
  # - UWaveGestureLibraryAll
  # - UWaveGestureLibraryX
  # - UWaveGestureLibraryY
  # - UWaveGestureLibraryZ
  # - Wafer
  # - Wine
  # - Worms
  # - WormsTwoClass
  # - Yoga