filename: tsfresh_eff.csv

device: cuda

runs: 30

models: 
  # - c22
  - tsfresh
  # - multirocket_fm
  # - DrCIF
  # - MiniRocket

data_path: data

seed: 0

datasets:

  # - Covid3Month
  # - FloodModeling1
  # - FloodModeling2
  # - FloodModeling3
  # - IEEEPPG
  # - HouseholdPowerConsumption2_nmv
  # - HouseholdPowerConsumption1_nmv
  # - AppliancesEnergy
  # - BenzeneConcentration_nmv
  # - LiveFuelMoistureContent
  # - BIDMC32RR
  # - BIDMC32SpO2
  # - BIDMC32HR

  # - AcousticContaminationMadrid_nmv
  # - AluminiumConcentration
  # - BarCrawl6min
  # - BeijingIntAirportPM25Quality
  # - BinanceCoinSentiment
  # - BitcoinSentiment
  # - BoronConcentration
  # - CalciumConcentration
  # - CardanoSentiment
  # - ChilledWaterPredictor
  # - CopperConcentration
  # - Covid19Andalusia
  # - DailyOilGasPrices
  # - DhakaHourlyAirQuality
  # - ElectricityPredictor
  # - EthereumSentiment
  # - GasSensorArrayAcetone
  # - GasSensorArrayEthanol
  # - HotwaterPredictor
  # - IronConcentration
  # - LPGasMonitoringHomeActivity
  # - MadridPM10Quality_nmv

  # - MagnesiumConcentration
  # - ManganeseConcentration
  # - MethaneMonitoringHomeActivity
  # - MetroInterstateTrafficVolume
  # - NaturalGasPricesSentiment
  # - OccupancyDetectionLight
  # - ParkingBirmingham_eq
  # - PhosphorusConcentration
  # - PotassiumConcentration
  # - PrecipitationAndalusia_nmv
  # - SierraNevadaMountainsSnow
  # - SodiumConcentration
  # - SolarRadiationAndalusia_nmv
  # - SteamPredictor
  # - SulphurConcentration
  # - WaveDataTension
  # - WindTurbinePower
  # - ZincConcentration
  # - BeijingPM10Quality_nmv
  # - BeijingPM25Quality_nmv
  
  # - ElectricMotorTemperature
  # - DailyTemperatureLatitude
  # - TetuanEnergyConsumption
  # - PPGDalia_eq
  # - NewsHeadlineSentiment
  # - NewsTitleSentiment
  # - VentilatorPressure
  # - AustraliaRainfall